// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rxemqnaxbkzizropsubj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ4ZW1xbmF4Ymt6aXpyb3BzdWJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5Nzk5MDEsImV4cCI6MjA2NTU1NTkwMX0.Z9d3uifo7MAfkYOtw58P5DZrB4AAKn7MJqHn4KIfEQk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);